### ISSUE TITLE
Project for Visual Studio 2015

### ISSUE THREAD

**Issue by ant-222** [zapadi/redmine-net-api#281]
Hello,

Is a project available for *Visual Studio 2015*?

**Comment by nicolassimoncini** [comment]
Hi @ant-222, What specifically do you need?

**Comment by ant-222** [comment]
The current version of your project works in *VS 2019*, but not i *VS 2015*. I just don't know how to run it from *Visual Studio 2015*. The syntax of your project file is unknown to me, so I thought I'd ask. Do you think it is possible to use your code inside a *Visual Studio 2015*? If it is, then I will try it again now and ask you help with specific problems, if you don't mind...

**Comment by nicolassimoncini** [comment]
Unless you mean forking the code because you want to improve something and pushing back (via a pull request) as a contribution, I don't see any reason to get all the code...  If you just want to use this project for accessing Redmine via its REST API , you only have to install the nugget package ([link](https://www.nuget.org/packages/redmine-api/)), start using it (you can check de "test" folder to get an idea) and that's it...

By the way, I'm not the ownder of the code.  I'm just a simple user.

**Comment by ant-222** [comment]
Well, it is easier for me to use the code from source control than having to store it in a separate binary. Thanks for reminding me about *nuget*, but I try to avoid it at all costs. OK, this time I can download the package, extract the DLL from it, and use that.

**Comment by stadub** [comment]
@ant-222 sorry for the late answer, VS 2015 and VS 2019 has different project formats (search msbuild on the msdn), if you need to make project run in the 2015 visual studio  you can try to create the proj file in the 2015 and transfer files from the 2019, but anyway it's not the best idea- easier will be just to use the correct VS version.
